version: '3.4'

services:
  chatapplication:
    image: ${DOCKER_REGISTRY-}chatapplication
    ports:
      - 5000:80    
      - 5001:443
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+;http://+
    build:
      context: .
      dockerfile: ChatApplication/Dockerfile
